In [1]:
# import 
import pandas as pd
import string
import re
from src.preprocesing import preprocesing_text
from src.tokenization import tokenizer

In [2]:
# read data
train_df = pd.read_csv("data/train.csv")
test_df = pd.read_csv("data/test.csv")
train_df

                                                 comment  label  label_id
0       غذا خیلی سرد بود در صورتیکه فاصله ما خیلی کم است    SAD       1.0
1         بهتره بتونیم ران یا سینه رو خودمون انتخاب کنیم  HAPPY       0.0
2      غذا بد بود حالم خیییییلی بده. دل دردو دل پیچه....    SAD       1.0
3      با سلام سابق بر این بسته بندی از کیفیت بهتری ب...    SAD       1.0
4                              سلام، خیلی ممنون و متشکرم  HAPPY       0.0
...                                                  ...    ...       ...
52105                یکی از بهترین ته چین هاییه که خوردم  HAPPY       0.0
52106                      به موقع و خوب دستتون درد نکنه  HAPPY       0.0
52107  خیلی تازه و خوشمزه بود. بسته بندی شیک وعالی. خ...  HAPPY       0.0
52108  فوق العاده سریع و عالی واقعا واسه همه زود آورد...  HAPPY       0.0
52109                             عالی بود وا قعا ممنونم  HAPPY       0.0

[52110 rows x 3 columns]

In [3]:
test_df

                                                comment  label  label_id
0     استرس داشتم نکنه که به خاطر تخفیف از کیفیت پای...  HAPPY       0.0
1                                      قاشق و نمک نداشت  HAPPY       0.0
2     سس مخصوص ساده‌ترین سس مایونزی بود که میشد تصور...    SAD       1.0
3                         به جای شامپو. نرم کننده اوردن    SAD       1.0
4                               یک غذای خوب وسالم ممنون    SAD       1.0
...                                                 ...    ...       ...
9028  بعضی از تیکه‌ها تند بود و در منو قید نشده بود....    SAD       1.0
9029  پیتزا گوشت و قارچ سفارش داده شده و نصف پیتزا ک...    SAD       1.0
9030                              عالی بود سریع ویخ زده  HAPPY       0.0
9031                        غذای خوبی بود نسبت به قیمتش  HAPPY       0.0
9032                         تمام شیرینی‌ها خرد شده بود    SAD       1.0

[9033 rows x 3 columns]

# EDA & preprocesing

In [4]:
train_df["label"].value_counts(), test_df["label"].value_counts()

(label
 HAPPY    26236
 SAD      25874
 Name: count, dtype: int64,
 label
 SAD      4547
 HAPPY    4486
 Name: count, dtype: int64)

In [5]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52110 entries, 0 to 52109
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   comment   52110 non-null  object
 1   label     52110 non-null  object
 2   label_id  52110 non-null  float64
dtypes: float64(1), object(2)
memory usage: 1.2+ MB

### check text for cleaning

In [6]:
# check url
train_df[train_df["comment"].str.contains("http", na= False)]

Empty DataFrame
Columns: [comment, label, label_id]
Index: []

In [7]:
# check mentions
train_df[train_df["comment"].str.contains("@", na= False)]

                                                 comment label  label_id
24236      بسیار رستوران بد و غذای سرد و بی کیفیت!!!!! @   SAD       1.0
34930  از زمان سفارش تا رسیدن پیتزا ۲ ساعت و ربع!!!!!...   SAD       1.0
36397  سفارش با یک ساعت تاخیر به دستمان رسید چرا اینق...   SAD       1.0
42184  متاسفانه سفار@ ثبت شده به تعدادرونداشتن تماس گ...   SAD       1.0

In [8]:
# check number
train_df[train_df["comment"].str.contains(r"\d", regex= True, na= False)]

                                                 comment  label  label_id
14     کیفیت پایین‌تر از پایین، در حد یه ساندویچ ۸-۹ ...    SAD       1.0
26     راد عزیز، متأسفانه دقت قبل در ارسال سفارش دیده...    SAD       1.0
29     اصلا فکر نمیکردم به این شدت غذا و کیفیتش پایین...    SAD       1.0
33     کیفیت بسیار بد!!! من ساندویچ ژامبون ویژه سفارش...    SAD       1.0
38     غذا بعد از ۱ ساعت و نیم با رفتار طلبکارانه پیک...    SAD       1.0
...                                                  ...    ...       ...
52088  به معنای واقعی عالی. چقدر تمیز و لایه لایه چید...  HAPPY       0.0
52092  طعم غذا به نسبت خوب بود منتها زمان رسید غذا خی...  HAPPY       0.0
52096  واقعا ۲۱ هزار تومان و مالیات ۲هزار تومنی برای ...    SAD       1.0
52099  سیب زمینی با قارچ و پنیر شامل ۲۰ عدد سیب زمینی...  HAPPY       0.0
52100  تنها حسنی که داشت زود رسید. تو توضیحات هم نوشت...  HAPPY       0.0

[4796 rows x 3 columns]

In [9]:
# check punctuation
punctuation = string.punctuation + "،؛«»٪" # !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~،؛«»٪
pattern = f"[{re.escape(punctuation)}]" # [!"\#\$%\&'\(\)\*\+,\-\./:;<=>\?@\[\\\]\^_`\{\|\}\~،؛«»٪]
train_df[train_df["comment"].str.contains(pattern, regex= True, na=False)]

                                                 comment  label  label_id
2      غذا بد بود حالم خیییییلی بده. دل دردو دل پیچه....    SAD       1.0
3      با سلام سابق بر این بسته بندی از کیفیت بهتری ب...    SAD       1.0
4                              سلام، خیلی ممنون و متشکرم  HAPPY       0.0
6      مواد پیتزا بسیااار کم بود با اینکه قیمت اصلا پ...  HAPPY       0.0
7                                   کیفیت زیاد خوب نبود،  HAPPY       0.0
...                                                  ...    ...       ...
52096  واقعا ۲۱ هزار تومان و مالیات ۲هزار تومنی برای ...    SAD       1.0
52100  تنها حسنی که داشت زود رسید. تو توضیحات هم نوشت...  HAPPY       0.0
52101  خیلی خوشمزه بودن فقط احساس کردم گوشت چرخ کرده‌...  HAPPY       0.0
52102  یه چیزی که برام جالبه و خیلی هم مهمه.. علاوه ب...  HAPPY       0.0
52107  خیلی تازه و خوشمزه بود. بسته بندی شیک وعالی. خ...  HAPPY       0.0

[26588 rows x 3 columns]

In [10]:
# apply clean text on dataframe

train_df["clean_text"] = train_df["comment"].apply(preprocesing_text)
test_df["clean_text"] = test_df["comment"].apply(preprocesing_text)

In [11]:
train_df["token"] = train_df["clean_text"].apply(lambda text : tokenizer(text, remove_stop_word=True))
test_df["token"] = test_df["clean_text"].apply(lambda text : tokenizer(text, remove_stop_word=True))

In [12]:
train_df

,comment,label,label_id,clean_text,token
0,غذا خیلی سرد بود در صورتیکه فاصله ما خیلی کم است,SAD,1.0,غذا خیلی سرد بود در صورتیکه فاصله ما خیلی کم است,"[غذا, سرد, صورتیکه, فاصله]"
1,بهتره بتونیم ران یا سینه رو خودمون انتخاب کنیم,HAPPY,0.0,بهتره بتونیم ران یا سینه رو خودمون انتخاب کنیم,"[بهتره, بتونیم, ران, سینه, خودمون, انتخاب]"
2,غذا بد بود حالم خیییییلی بده. دل دردو دل پیچه....,SAD,1.0,غذا بد بود حالم خیلی بده دل دردو دل‌پیچه معلوم...,"[غذا, بد, حالم, بده, دل, دردو, دل‌پیچه, معلوم,..."
3,با سلام سابق بر این بسته بندی از کیفیت بهتری ب...,SAD,1.0,با سلام سابق بر این بسته بندی از کیفیت بهتری ب...,"[سلام, سابق, بسته, کیفیت, بهتری, برخوردار, حاض..."
4,سلام، خیلی ممنون و متشکرم,HAPPY,0.0,سلام خیلی ممنون و متشکرم,"[سلام, ممنون, متشکرم]"
...,...,...,...,...,...
52105,یکی از بهترین ته چین هاییه که خوردم,HAPPY,0.0,یکی از بهترین ته چین هاییه که خوردم,"[ته, چین, هاییه, خوردم]"
52106,به موقع و خوب دستتون درد نکنه,HAPPY,0.0,به موقع و خوب دستتون درد نکنه,"[موقع, دستتون, درد, نکنه]"
52107,خیلی تازه و خوشمزه بود. بسته بندی شیک وعالی. خ...,HAPPY,0.0,خیلی تازه و خوشمزه بود بسته بندی شیک وعالی خدا...,"[تازه, خوشمزه, بسته, شیک, وعالی, خدابرکت, بده,..."
52108,فوق العاده سریع و عالی واقعا واسه همه زود آورد...,HAPPY,0.0,فوق‌العاده سریع و عالی واقعا واسه همه زود آورد...,"[فوق‌العاده, سریع, واقعا, واسه, زود, آوردنات, ..."
52109,عالی بود وا قعا ممنونم,HAPPY,0.0,عالی بود وا قعا ممنونم,"[وا, قعا, ممنونم]"

# train & test split

In [13]:
X_train = train_df["clean_text"]
y_train = train_df["label_id"]

X_test = test_df["clean_text"]
y_test = test_df["label_id"]

# TF-IDF

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import f1_score, accuracy_score, confusion_matrix, classification_report, ConfusionMatrixDisplay
from hazm.utils import stopwords_list

In [15]:
# create tfidf
stop_words = stopwords_list()
vectorize = TfidfVectorizer(
    max_features=15000,
    max_df=90,
    stop_words= stop_words,
    min_df= 5,
    ngram_range=(1, 2)
)

X_train_tfidf = vectorize.fit_transform(X_train)
X_test_tfidf = vectorize.transform(X_test)

models = {
    "LogisticRegression" : LogisticRegression(),
    "LinearSVC" : LinearSVC(),
    "MultinomialNB" : MultinomialNB()
}

# train model
results = []
for name, model in models.items():
    model.fit(X_train_tfidf, y_train)
    predict = model.predict(X_test_tfidf)
    acc = accuracy_score(y_test, predict)
    f1 = f1_score(y_test, predict)
    results.append({"approach": "TF-IDF", "model": name, "accuracy": acc, "f1": f1})
    print(f"=== {name} (TF-IDF) ===")
    print(classification_report(y_test, predict, target_names=['HAPPY','SAD']))

/home/milad/projects/env/lib/python3.11/site-packages/sklearn/feature_extraction/text.py:412: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['آید', 'توان', 'تواند', 'توانند', 'رسد', 'رود', 'سال', 'نمی', 'های', 'گوید', 'گویند'] not in stop_words.
  warnings.warn(

=== LogisticRegression (TF-IDF) ===
              precision    recall  f1-score   support

       HAPPY       0.75      0.77      0.76      4486
         SAD       0.77      0.75      0.76      4547

    accuracy                           0.76      9033
   macro avg       0.76      0.76      0.76      9033
weighted avg       0.76      0.76      0.76      9033

=== LinearSVC (TF-IDF) ===
              precision    recall  f1-score   support

       HAPPY       0.74      0.77      0.76      4486
         SAD       0.76      0.73      0.75      4547

    accuracy                           0.75      9033
   macro avg       0.75      0.75      0.75      9033
weighted avg       0.75      0.75      0.75      9033

=== MultinomialNB (TF-IDF) ===
              precision    recall  f1-score   support

       HAPPY       0.77      0.76      0.77      4486
         SAD       0.77      0.78      0.77      4547

    accuracy                           0.77      9033
   macro avg       0.77      0.77      0.77      9033
weighted avg       0.77      0.77      0.77      9033

# word2vec

In [16]:
from gensim.models import Word2Vec
import numpy as np

In [17]:
sentences = train_df["token"].to_list()
w2v_model = Word2Vec(
    sentences= sentences,
    vector_size= 100,
    window= 3,
    min_count= 5,
    epochs= 100,
    sg= 1
)

In [18]:
w2v_model.wv['خوشمزه']

array([ 0.36146244,  0.0981238 , -0.04876146, -0.2090513 ,  0.0534662 ,
       -0.3660064 , -0.39140046,  0.1771994 , -0.1362751 , -0.00481967,
       -0.24077757, -0.3476517 ,  0.18860792,  0.140763  ,  0.16988069,
       -0.13517998,  0.15604062, -0.44289666,  0.01440858, -0.26067287,
        0.2505115 ,  0.06560814, -0.19875465, -0.37846687, -0.02298697,
       -0.00641999, -0.32759693,  0.1831345 , -0.13791485,  0.3048164 ,
        0.38221753, -0.16747908,  0.08944332, -0.46723685, -0.19200295,
        0.31756854, -0.11434729,  0.03037162,  0.14030114, -0.02933482,
        0.0969149 , -0.08579095,  0.07817209,  0.07574669,  0.3830115 ,
        0.45187166, -0.10170163, -0.08670966,  0.2628743 , -0.03562219,
        0.2799386 , -0.20673512,  0.16172329,  0.11452065,  0.05519499,
       -0.07112488, -0.08458615,  0.2238138 ,  0.12612559,  0.4881189 ,
        0.33937898, -0.03469697,  0.01895845,  0.07171457,  0.04185758,
        0.11884557,  0.08161446,  0.32628182, -0.6061131 , -0.02638512,
        0.04216518,  0.12020212,  0.31238168, -0.18470772,  0.2210539 ,
       -0.15279597,  0.31635723, -0.0918733 , -0.10711192, -0.24726194,
       -0.2524587 ,  0.34486285, -0.00974443,  0.3684352 ,  0.21719931,
       -0.39031553,  0.24352328,  0.15465946,  0.44049093,  0.11513513,
        0.07999933,  0.01799878, -0.48285344, -0.19076507,  0.10450754,
        0.08883259,  0.01470222, -0.43145692,  0.05916566, -0.04076289],
      dtype=float32)

In [19]:
w2v_model.wv.most_similar('خوشمزه', topn=5)

[('خوش\u200cطعم', 0.7855303883552551),
 ('خوش\u200cمزه', 0.7042403817176819),
 ('لذیذ', 0.678156852722168),
 ('تازه', 0.6039243340492249),
 ('خوشمزه\u200cای', 0.5770860910415649)]

In [24]:
# create on sentence with words in sentence

def sentence_to_vec(tokens, model, dim= 100):
    vector = [model.wv[w] for w in tokens if w in model.wv]
    if len(vector) == 0:
        return np.zeros(dim)
    return np.mean(vector, axis=0)


X_train_emb = []
X_test_emb = []

for token in train_df["token"]:
    vec = sentence_to_vec(token, w2v_model)
    X_train_emb.append(vec)
X_train_emb = np.array(X_train_emb)


for token in test_df["token"]:
    vec = sentence_to_vec(token, w2v_model)
    X_test_emb.append(vec)
X_test_emb = np.array(X_test_emb)

In [25]:
X_train_emb[:5]

array([[-1.20767459e-01,  1.01883113e-01,  2.22383738e-02,
        -4.55788039e-02, -3.11101317e-01,  1.39642239e-01,
         4.39728528e-01,  5.40857553e-01, -3.02010894e-01,
        -1.94700837e-01,  1.35806456e-01, -2.95224875e-01,
        -3.52071285e-01,  3.33750904e-01,  1.60314441e-02,
        -1.36963978e-01, -7.30421990e-02,  3.61957967e-01,
        -2.63110638e-01, -2.92067230e-01,  1.16012186e-01,
         9.80601162e-02,  1.91727877e-01, -2.54610509e-01,
        -1.39365226e-01, -1.86918095e-01, -2.80898869e-01,
         1.73735678e-01, -1.77172065e-01,  2.02389210e-02,
        -1.18636370e-01, -1.16212498e-02,  1.96844757e-01,
        -2.87149735e-02, -3.89320493e-01,  1.81113631e-01,
         2.09853053e-01, -7.29210302e-02,  1.92312419e-01,
        -1.37829289e-01,  2.30653733e-01, -3.68802667e-01,
        -1.32564455e-01, -1.06288724e-01,  8.56952220e-02,
        -2.31557727e-01, -1.23963133e-01,  5.77983931e-02,
         3.27566326e-01,  2.43797719e-01,  2.59958953e-01,
        -4.13536042e-01, -2.95213401e-01,  9.28687081e-02,
        -1.28802121e-01,  1.20246202e-01,  8.22024271e-02,
        -2.01443702e-01,  1.17292264e-02,  8.17735773e-03,
        -6.15579262e-03,  2.52622545e-01, -1.08998053e-01,
         9.57895517e-02, -1.10376909e-01,  5.04569352e-01,
         8.13328251e-02,  9.89317745e-02, -6.06258631e-01,
         1.13686591e-01,  2.98171997e-01,  6.67272091e-01,
         3.71273965e-01,  1.10454805e-01,  2.61939526e-01,
         2.85833746e-01,  4.18812148e-02, -8.69563222e-03,
         1.63176864e-01, -1.80640087e-01, -1.81215495e-01,
        -5.69440722e-01,  6.39038756e-02,  1.90589815e-01,
         4.59641814e-02, -4.17412743e-02,  1.55401647e-01,
        -1.19384341e-02,  1.82535738e-01,  2.64931396e-02,
         1.33691773e-01,  4.79433499e-02,  1.34163657e-02,
         1.27352759e-01,  1.06140554e-01,  4.08364952e-01,
         3.06571484e-01, -8.31868500e-03, -1.08655646e-01,
        -5.83191030e-03],
       [-4.73742753e-01, -4.88903075e-01, -4.61685032e-01,
         2.22553089e-01,  1.10912241e-01, -2.03618363e-01,
         2.23420277e-01,  5.01765788e-01, -1.74923822e-01,
        -1.45175889e-01, -7.29924953e-03, -2.58263141e-01,
         6.76731691e-02, -2.75371879e-01,  7.57473230e-04,
        -3.72680187e-01, -3.35736386e-02, -4.72791791e-01,
         9.55968797e-02, -2.91417956e-01,  9.82166827e-03,
         6.71232224e-01,  1.64849162e-01,  5.81113845e-02,
        -9.06109214e-02,  5.48446663e-02, -4.15184110e-01,
        -1.36039570e-01, -4.04611617e-01,  8.91602859e-02,
         1.27778307e-01,  1.66590640e-03, -8.71824920e-02,
        -2.06787810e-01, -3.03626984e-01,  2.51870543e-01,
         2.64518887e-01, -3.71506214e-01,  1.83958218e-01,
        -5.38323343e-01, -4.86141182e-02, -7.29434550e-01,
         1.38624176e-01, -6.80618808e-02,  3.84245187e-01,
        -3.04432362e-01,  2.32185051e-01, -6.46617040e-02,
        -3.56452614e-01,  3.46968502e-01,  4.36838381e-02,
         1.77323714e-01, -2.00772360e-01,  1.71475410e-01,
        -3.16172689e-01,  5.31378448e-01,  4.71368909e-01,
        -8.83074626e-02, -4.37967926e-01,  2.55623311e-01,
         7.18869939e-02,  3.44600469e-01, -2.32418552e-01,
         1.93075836e-01, -6.76383227e-02,  1.38248220e-01,
         4.01691198e-01,  5.10532968e-02, -2.43624404e-01,
         5.74606597e-01, -2.65726477e-01,  2.36216500e-01,
        -2.33498856e-01, -4.44338113e-01, -2.06123352e-01,
        -1.49132326e-01,  4.05923694e-01,  3.96331474e-02,
        -1.54129520e-01,  3.05857867e-01, -8.39679409e-03,
         1.27398059e-01,  9.92486849e-02,  2.04362556e-01,
         9.92631540e-03, -1.58858344e-01, -1.00264847e-02,
         4.96752948e-01,  4.26860660e-01, -2.31513456e-01,
         1.91037014e-01,  2.96242505e-01,  2.14814305e-01,
         6.75755888e-02,  1.17187910e-01,  8.39087740e-03,
         5.57303846e-01, -1.08717658e-01,  8.43869224e-02,
         7.52235800e-02],
       [-5.50643578e-02,  2.46332601e-01,  9.14407372e-02,
        -4.07823533e-01, -1.31116852e-01, -2.16862172e-01,
        -4.64116074e-02,  4.61164504e-01, -3.29728425e-02,
        -5.61672188e-02, -1.06275536e-01,  2.42288616e-02,
        -1.18486509e-01,  1.20657541e-01,  8.48478153e-02,
        -3.82961482e-01, -4.02120128e-02, -3.30552310e-01,
        -1.11508064e-01, -1.64977297e-01,  2.65484363e-01,
        -1.68594331e-01,  2.06991643e-01,  1.09423272e-01,
        -3.89826819e-02, -1.10827491e-01, -1.51916459e-01,
        -1.81106806e-01, -2.99289286e-01, -3.30526158e-02,
        -2.93078870e-01, -2.35353447e-02,  2.30986223e-01,
        -1.67842671e-01,  2.21691519e-01,  2.59882927e-01,
         8.82456973e-02, -1.33363053e-01, -2.90804118e-01,
        -2.54533321e-01, -2.66387522e-01, -1.08997539e-01,
         2.86429264e-02, -6.85407668e-02,  3.06190342e-01,
         3.26615646e-02, -1.16671205e-01,  7.44489655e-02,
         2.60875076e-02,  3.13224867e-02,  1.90345570e-01,
        -2.32918337e-01,  7.01060295e-02,  6.13664016e-02,
        -1.02338731e-01, -1.24621645e-01, -1.17239781e-01,
        -1.04779981e-01, -1.91988796e-01,  3.81091863e-01,
        -2.16229394e-01, -3.50419916e-02, -1.59559518e-01,
        -2.07476020e-01,  5.43018319e-02,  1.67150512e-01,
         4.90675829e-02,  2.83993453e-01, -2.10181266e-01,
         3.31847578e-01, -2.38567695e-01,  9.51313376e-02,
         5.00944614e-01,  1.10204764e-01,  2.96859592e-01,
         1.31415829e-01,  1.14567474e-01, -6.62830248e-02,
         1.22782839e-02,  3.44599187e-01,  2.30846658e-01,
        -3.08631331e-01, -1.93042442e-01,  5.54183364e-01,
        -1.32739037e-01,  7.00770766e-02, -1.35291308e-01,
         2.96679527e-01,  1.29594654e-01,  2.17905954e-01,
         4.27069038e-01, -1.02797322e-01,  5.31306199e-04,
         9.35988277e-02,  5.70188686e-02,  4.78255272e-01,
         3.66783381e-01, -8.50790888e-02, -7.52771124e-02,
        -2.65815884e-01],
       [ 2.53405678e-03,  1.55723020e-02,  1.28235415e-01,
         2.31740087e-01, -3.37510221e-02, -2.43711695e-01,
        -5.29345497e-02,  4.02798504e-01, -2.35477492e-01,
         4.65015024e-02, -1.85432974e-02, -3.42900932e-01,
        -5.37866987e-02,  1.02747545e-01,  1.98526561e-01,
        -5.45916669e-02, -1.27448246e-01, -1.64528728e-01,
        -6.88222945e-02, -4.69083637e-01,  7.93062523e-02,
         1.00380912e-01,  1.54058173e-01, -1.52705967e-01,
         7.68458098e-02,  4.65723174e-03, -2.39597619e-01,
         1.81085840e-01, -8.74982327e-02,  2.04144176e-02,
         3.75919104e-01, -2.21150264e-01,  2.61727005e-01,
        -2.85089523e-01,  1.22945365e-02,  4.89423200e-02,
         1.25640318e-01, -1.34841293e-01,  1.46258790e-02,
        -1.16026141e-01,  1.01979291e-02, -4.11272466e-01,
        -2.60286391e-01, -1.93267822e-01,  5.56748025e-02,
        -2.94711173e-01, -1.13929018e-01,  1.46404076e-02,
         2.87369229e-02,  5.71599640e-02,  3.37825298e-01,
        -9.88614783e-02, -1.95769276e-02,  2.39098772e-01,
        -1.01975426e-01,  1.01785094e-01,  1.08969063e-01,
         6.13959245e-02, -4.70016986e-01,  2.17266735e-02,
         2.53556967e-01,  3.13891292e-01,  1.13441944e-02,
         8.95101428e-02, -2.09256858e-01,  2.88904101e-01,
         8.92020613e-02,  2.70467997e-01, -9.08639003e-03,
         1.02157377e-01, -1.35856286e-01,  9.69453529e-02,
         2.82425843e-02,  8.66174698e-02,  1.33987427e-01,
         5.22019506e-01, -9.73673351e-03, -2.46963546e-01,
         3.34729999e-02, -3.27873800e-04, -2.05919370e-02,
        -1.89700976e-01, -1.49046332e-01,  2.07944646e-01,
        -2.09087238e-01,  1.88171864e-01,  5.61539792e-02,
         2.95409769e-01,  1.84482515e-01,  2.09893271e-01,
         5.28168499e-01,  8.87184739e-02,  2.34070476e-02,
        -7.99388289e-02,  3.12362939e-01,  7.15989023e-02,
         2.25416452e-01, -1.98716134e-01, -1.54572561e-01,
         6.10284396e-02],
       [-2.32827663e-02, -2.21202821e-02, -4.57341671e-02,
         1.01246238e-01,  2.82929868e-01, -7.15994298e-01,
        -1.40691400e-01,  2.46802017e-01, -3.12050819e-01,
        -1.25565901e-01, -2.26762369e-01, -4.22692485e-02,
         2.01850340e-01,  1.10441864e-01,  5.21244228e-01,
        -3.31810117e-03, -1.12991132e-01, -2.94058591e-01,
        -6.43669516e-02, -5.50433636e-01,  2.18726084e-01,
         2.38303408e-01,  3.63471992e-02, -4.01336908e-01,
        -2.45411322e-01,  8.30690935e-02, -3.13977510e-01,
        -3.32500041e-03, -2.05839559e-01,  4.62344795e-01,
         5.41938782e-01, -1.41553059e-01,  1.59413461e-02,
         1.73736215e-01, -3.02291989e-01,  2.17200145e-01,
         2.04194877e-02, -8.04963708e-03,  1.25241116e-01,
        -4.03674126e-01,  7.99921080e-02, -1.62368238e-01,
         1.77552626e-01, -1.88872755e-01, -1.16940163e-01,
        -2.80960649e-02, -2.04400793e-01,  1.77792430e-01,
         3.18153352e-01, -4.56162453e-01,  1.87229440e-01,
        -9.26894546e-02,  1.97384477e-01, -3.19433421e-01,
        -1.85798109e-03, -3.13522369e-01, -1.52081415e-01,
        -1.93806112e-01,  7.37437531e-02,  1.00511126e-01,
         3.43421221e-01,  2.46914532e-02,  3.39861840e-01,
         1.30515443e-02, -2.32979897e-02,  2.21426487e-01,
         1.73889086e-01,  1.01764100e-02, -6.20564997e-01,
         3.99542928e-01, -2.83371091e-01,  1.56161889e-01,
         3.33505839e-01,  2.55350858e-01,  2.30957851e-01,
        -1.14237927e-01,  9.08207614e-03, -2.23725483e-01,
        -3.43693405e-01, -5.87942488e-02, -5.75442500e-02,
        -1.74450874e-02, -1.84871987e-01,  1.25009537e-01,
         9.78835151e-02,  1.18373968e-01, -1.35222077e-01,
         7.93493018e-02,  3.72041613e-01, -1.03271110e-02,
         2.85156816e-01,  6.48225993e-02, -3.60332876e-01,
        -2.94071227e-01,  1.08197272e-01,  1.08731143e-01,
        -1.21700503e-01, -2.88069218e-01,  8.18724558e-02,
         2.11281538e-01]])

In [26]:
from sklearn.neural_network import MLPClassifier

In [27]:
model_emb = {
    "LogisticRegression" : LogisticRegression(max_iter= 1000),
    "LinearSVC" : LinearSVC(),
    "NLP_nn : " : MLPClassifier(hidden_layer_sizes=(100,), max_iter=500, random_state= 42)
}

emb_results = []
for name, model in model_emb.items():
    model.fit(X_train_emb, y_train)
    predict = model.predict(X_test_emb)
    acc = accuracy_score(y_test, predict)
    f1 = f1_score(y_test, predict)
    emb_results.append({"model": name, "accuracy": acc, "f1": f1})

    print(f"=== {name} ===")
    print(classification_report(y_test, predict, target_names=['HAPPY', 'SAD']))

=== LogisticRegression ===
              precision    recall  f1-score   support

       HAPPY       0.84      0.75      0.79      4486
         SAD       0.78      0.86      0.82      4547

    accuracy                           0.80      9033
   macro avg       0.81      0.80      0.80      9033
weighted avg       0.81      0.80      0.80      9033

=== LinearSVC ===
              precision    recall  f1-score   support

       HAPPY       0.85      0.74      0.79      4486
         SAD       0.77      0.87      0.82      4547

    accuracy                           0.81      9033
   macro avg       0.81      0.81      0.81      9033
weighted avg       0.81      0.81      0.81      9033

=== NLP_nn :  ===
              precision    recall  f1-score   support

       HAPPY       0.78      0.77      0.78      4486
         SAD       0.78      0.79      0.78      4547

    accuracy                           0.78      9033
   macro avg       0.78      0.78      0.78      9033
weighted avg       0.78      0.78      0.78      9033

/home/milad/projects/env/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

# save model

In [30]:
import joblib

joblib.dump(model_emb["LinearSVC"], "model/linear_svc.pkl")

w2v_model.save("model/word2vec.model")